spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:8848
        metadata:
          paths:
            - /admin/admin/**
            - /admin/adminNotification/*
            - /admin/adminDashboard/*
            - /admin/adminUser/*
            - /admin/adminResource/*
            - /admin/adminRole/*
            - /admin/adminJob/*
            - /admin/adminConfigGroup/*
            - /admin/adminConfig/*
            - /admin/uploadFile/*
            - /admin/codeTable/*
            - /admin/codeTableTemplateGroup/*
            - /admin/codeTableTemplate/*
            - /admin/adminUserLoginLog/*
            - /admin/adminDict/*
            - /admin/adminEmailTemplate/*
            - /admin/adminSmsTemplate/*
            - /admin/adminOperationLog/*
            - /admin/adminRelease/*
            - /login/config
            - /login
          routeOrder: 1000000
          moduleName: admin
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:soho-admin-cloud-base.yml
      - optional:nacos:soho-admin-cloud-base-@profiles.active@.yml
      - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
server:
  servlet:
    encoding:
      charset: utf-8
  port: 6678